# Sniperkit-Bot
# - Date: 2018-08-11 23:49:10.5425416 +0200 CEST m=+0.207409358
# - Status: analyzed

sudo: false

language: go

# Whenever the Go version is updated here, .circleci/config.yml should also be
# updated.
go:
- 1.10.x

go_import_path: github.com/sniperkit/snk.fork.prometheus

script:
- make check_license style unused test staticcheck
