# Sniperkit-Bot
# - Date: 2018-08-11 23:49:10.5425416 +0200 CEST m=+0.207409358
# - Status: analyzed

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  ports:
  - port: 9090
    name: exporter
    targetPort: exporter
    protocol: TCP
  selector:
    app: rabbitmq
